### ISSUE TITLE
프로바이더 별 워크스페이스 분리

### ISSUE THREAD

**Issue by lens0021** [femiwiki/infra#11]
github과 aws를 같은 워크스페이스에 담다보니 한 쪽만 변경하여도 양쪽 스테이트 업데이트를 모두 하여 시간이 좀 더 소요됩니다.

서브디렉토리를 만들어 둘로 나눌까요??

**Comment by simnalamburt** [comment]
네

**Comment by lens0021** [comment]
#### TODO

- [x] [app.terraform.io]에 github 워크스페이스 생성 → 작업 중에 뭐 잘못 했더니 지가 알아서 생겼음
- [ ] `terraform state pull > foo` 한 뒤 github 부분만 백업
- [ ] 디렉토리 나누기 `base.tf` 수정
- [ ] 위에서 백업한 github state push

[app.terraform.io]: https://app.terraform.io/

**Comment by lens0021** [comment]
나눴습니다~ workspace 중에 "infra"는 "aws"로 바꿀까 하다가 여쭤보려고 말았는데 어떻게 할까요?

**Comment by simnalamburt** [comment]
aws로 바꾸죠

**Comment by lens0021** [comment]
Closed by https://github.com/femiwiki/infra/commit/8d23ec7595cd4ca6493fa943ceb39588da27458a
